function printMultiplicationTables() {
    const size = 11; 
    let header = "    "; 
  
    // construimos la cabecera
    for (let i = 1; i <= size; i++) {
      header += i.toString().padStart(4, " ");
    }
    console.log(header);
  
    // construimos cada fila
    for (let row = 1; row <= size; row++) {
      let line = row.toString().padStart(4, " "); // primera columna (número de fila)
      for (let col = 1; col <= size; col++) {
        line += (row * col).toString().padStart(4, " ");
      }
      console.log(line);
    }
  }
  
  

printMultiplicationTables()
// expected output
//     1   2   3   ...
// 1   1   2   3   ...
// 2   2   4   6   ...
// 3   3   6   9   ...
// 4   4   8   12  ...
// 5   5   10  15  ...
// 6   6   12  18  ...
// 7   7   14  21  ...
// 8   8   16  24  ...
// 9   9   18  27  ...
// 10  10  20  30  ...
